# Generated by Django 5.0.4 on 2024-04-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_rename_user_escola_usuarios_escola_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuarios",
            name="turma",
            field=models.CharField(max_length=7, null=True),
        ),
    ]
