# Generated by Django 5.0.4 on 2024-04-04 20:49

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0004_mymodel_remove_usuarios_id_aluno_model_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuarios",
            name="cpf",
            field=cpf_field.models.CPFField(
                max_length=14, primary_key=True, serialize=False
            ),
        ),
    ]
