# Generated by Django 5.0.4 on 2024-04-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0005_alter_usuarios_cpf"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyModel",
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="cpf",
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
