# Generated by Django 5.0.4 on 2024-04-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_mymodel_alter_usuarios_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
